#!/bin/bash

diagonals=(
	"45b_56t"
	"45t_56b"
)

configurations=(
	"fitN-2/none"

	"fitN-2/sh-thx"
	"fitN-2/sh-thx-LRasym"

	"fitN-2/sh-thy"
	"fitN-2/sh-thy-LRasym"
	"fitN-2/sh-thy-TBuncor"
	"fitN-2/sh-thy-TBuncor-LRasym"

	"fitN-2/tilt-thx-thy"
	"fitN-2/tilt-thx-thy-LRasym"

	"fitN-2/sc-thxy-mode1"
	"fitN-2/sc-thxy-mode2"
	"fitN-2/sc-thxy-mode3"

	"fitN-2/dx-sigma"
	"fitN-2/dy-sigma"
	"fitN-2/dx-non-gauss"

	"fitN-2/eff-intercept"
	"fitN-2/eff-slope"

	"fitN-2/beam-mom"

	"fitN-2/mx-sigma"
	"fitN-2/my-sigma"

	"fitN-2/norm"

	"fitN-4/none"
)

use_lxbatch="n"
bsub_options="pool>1"
bsub_queue="1nh"

#----------------------------------------------------------------------------------------------------

function ExecuteOne()
{
	echo "* $dir/$scenario"

	local cwd=`pwd -P`

	local tag="$scenario"

	local job_dir="$cwd"
	local job_file="$dir/.${tag}.job"
	local job_log_file="$dir/.${tag}.log_job"

	local command="{ time ./ni_simu -model \"$model\" -diagonal \"$diagonal\" -scenario \"$scenario\" -output \"$dir/$scenario.root\" ; } \&> \"$dir/$scenario.log\""

	cat "job_template" | sed "\
			s|\$JOB_DIR|$job_dir|; \
			s|\$JOB_LOG_FILE|$job_log_file|; \
			s|\$COMMAND|$command|; \
		" > "$job_file"
	chmod u+x "$job_file"

	if [ "$use_lxbatch" == "n" ]
	then
		"./$job_file" &
	else
		result=`bsub -R "$bsub_options" -q "$bsub_queue" -o /dev/null -e /dev/null "$cwd/$job_file"`
		echo "    $result"
	fi
}

#----------------------------------------------------------------------------------------------------

make "ni_simu" || exit 1

for diagonal in ${diagonals[*]}
do
	for configuration in ${configurations[*]}
	do
		model=${configuration%%/*}
		scenario=${configuration##*/}

		dir="data-ni/$diagonal/$model"
		mkdir -p "$dir"

		ExecuteOne
	done
done
