#!/bin/bash

configs=()
config_options=()

configs=(
#	"0.013 1E7 old flat"
	"0.013 1E7 new flat"
	"0.013 1E7 new curved"
)

#config+=("t_max=0.10,events=1E6,old"); config_options+=("-t-max 0.1 -events 1E6 -old-acc")

seeds=(
	1
	2
	3
)

#----------------------------------------------------------------------------------------------------

#batch_queue="8nm"
batch_queue="1nh"

batch_resources=""
#batch_resources="pool>10000" # require more than 10 GB of space in the pool directory

#batch_options=""
batch_options="-o /dev/null -e /dev/null"

#----------------------------------------------------------------------------------------------------

function ParseConfig
{
	t_max="$1"
	events="$2"
	alg="$3"
	cuts="$4"
}

#----------------------------------------------------------------------------------------------------

function SubmitOne()
{
	echo "$dir | $options"

	mkdir -p "$dir"

	job_file="$dir/job"

	# make job script
	cat "job_template" | sed "
			s|\$options|$options|g;	
			s|\$output|$dir/validation_with_mc.root|g;	
			s|\$log|$dir/log|g;	
		" > "$job_file"

	chmod u+x "$job_file"

	# submit job
	#bsub -q "$batch_queue" -R "$batch_resources" $batch_options `pwd -P`"/$job_file"
	"$job_file" &
}

#----------------------------------------------------------------------------------------------------

for config in "${configs[@]}"
do
	ParseConfig $config

	for seed in ${seeds[*]}
	do
		dir="simulations/$t_max,$events,$alg,$cuts/seed$seed"
		options="-t-max $t_max -events $events -alg-$alg -cuts-$cuts -seed $seed"

		SubmitOne
	done
done
