#!/bin/bash

datasets=(
	"DS-fill5313"
)

diagonals=(
	"45b_56t"
	"45t_56b"
)

scenarios=(
	"none"
	"alig-sh-thx"
	"alig-sh-thy"
	"thx-thy-tilt"
	"opt-m1"
	"opt-m2"
)

N_ev="1E8"

lxbatch="y"

bsub_options="pool>1"
bsub_queue="8nh"

#----------------------------------------------------------------------------------------------------

function RunOneDiagonal()
{
	echo "* $ds, $dgn"

	for scenario in ${scenarios[*]}
	do
		subdir="$ds/$dgn/simu_direct_$scenario"
		tag="$N_ev"

		mkdir -p "$subdir"

		local cwd=`pwd -P`
		local job_dir="$cwd"
		local job_file="$subdir/.${tag}.job"
		local job_log_file="$subdir/.${tag}.log_job"

		cat "job_template" | sed "\
				s|\$JOB_DIR|$job_dir|; \
				s|\$JOB_LOG_FILE|$job_log_file|; \
				s|\$COMMAND|{ time ./simu_direct \"$ds\" \"$dgn\" \"$scenario\" \"$N_ev\" \"$subdir/${tag}.root\" ; } \&> \"$subdir/${tag}.log\"|; \
			" > "$job_file"
		chmod u+x "$job_file"

		if [ "$lxbatch" == "n" ]
		then
			"./$job_file" &
		else
			result=`bsub -R "$bsub_options" -q "$bsub_queue" -o /dev/null -e /dev/null "$cwd/$job_file"`
			echo "    $result"
		fi
	done
}
#----------------------------------------------------------------------------------------------------

function RunOneDataset()
{
	for dgn in ${diagonals[*]}
	do
		RunOneDiagonal &
	done

	wait

	# TODO
	#tag="$ds/matrix_numerical_integration"
	#./matrix_numerical_integration "${ds}" "${tag}.root" &> "${tag}.log"
}

#----------------------------------------------------------------------------------------------------

make "simu_direct" || exit 1

# TODO
#make "matrix_numerical_integration" || exit 3

for ds in ${datasets[*]}
do
	RunOneDataset &
done
